version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: devdb
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: StockSavvy
    ports:
      - "5432:5432"
    networks:
      - db_network

networks:
  db_network:
    driver: bridge
